project: 'walker-project'
program: deps/baselines/main.py
method: grid
name: Walker-bcf

parameters:
  seed:
    values: [1, 2, 3, 4, 5]
  prefix:
    value: bcf
  alg:
    value: bcf
  traj-load-path:
    value: modril/expert_datasets/walker.pt
  env-name:
    value: "Walker2d-v3"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 1000
  eval-num-processes:
    value: 10
  cuda:
    value: True
  num-render:
    value: 0
  num-eval:
    value: 10
  vid-fps:
    value: 100
  lr:
    value: 0.0001
  log-interval:
    value: 1000
  save-interval:
    value: 100000
  eval-interval:
    value: 1000
  bc-state-norm:
    value: True
  clip-actions:
    value: True
  num-env-steps:
    value: 5000000