project: 'walker-project'
program: deps/baselines/main.py
method: grid
name: Walker-drail-un
command:
  - ${env}
  - python3
  - ${program}
  - ${args}

parameters:
  action-input:
    value: false
  drail-reward-norm:
    value: true
  drail-state-norm:
    value: true
  alg:
    value: drail-un
  clip-actions:
    value: true
  cuda:
    value: true
  disc-lr:
    value: 0.0001
  discrim-depth:
    value: 4
  discrim-num-unit:
    value: 1024
  entropy-coef:
    value: 0.001
  env-name:
    value: Walker2d-v3
  eval-interval:
    value: 20000
  eval-num-processes:
    value: 1
  log-interval:
    value: 1
  lr:
    value: 0.0001
  max-grad-norm:
    value: 0.5
  normalize-env:
    value: true
  num-env-steps:
    value: 25000000
  num-epochs:
    value: 10
  num-eval:
    value: 2
  num-mini-batch:
    value: 32
  num-render:
    value: 1000
  num-steps:
    value: 128
  ppo-hidden-dim:
    value: 256
  prefix:
    value: drail-un
  reward-type:
    value: airl-positive
  save-interval:
    value: 100000
  seed:
    values: [1,2,3,4,5]
  traj-batch-size:
    value: 128
  traj-frac:
    value: 1
  traj-load-path:
    value: modril/expert_datasets/walker.pt
  vid-fps:
    value: 100