project: 'walker-project'
program: deps/baselines/main.py
method: grid
name: Walker-drail
command:
  - ${env}
  - python3
  - ${program}
  - ${args}

parameters:
  seed:
    values: [1, 2, 3, 4, 5]
  prefix:
    value: "drail"
  alg:
    value: "drail"
  traj-load-path:
    value: modril/expert_datasets/ppo_walker_5.pt
  env-name:
    value: "Walker2d-v3"
  normalize-env:
    value: True
  cuda:
    value: True
  eval-num-processes:
    value: 1
  num-render:
    value: 1000
  num-eval:
    value: 2
  vid-fps:
    value: 100
  log-interval:
    value: 1
  save-interval:
    value: 100000
  eval-interval:
    value: 2000
  clip-actions:
    value: True
  traj-batch-size:
    value: 128
  max-grad-norm:
    value: 0.5
  num-env-steps:
    value: 25000000
  traj-frac:
    value: 1
  action-input:
    value: False
  entropy-coef:
    value: 0.001
  num-steps:                # Update policy storage's length
    value: 128
  num-epochs:               # Update policy epock
    value: 10
  num-mini-batch:           # For update policy
    value: 32
  drail-state-norm:
    value: True
  drail-reward-norm:
    value: True
  lr:
    value: 0.0001            # noise 2.00
  disc-lr:
    value: 0.0001         # noise 2.00
  discrim-num-unit:
    value: 1024
  discrim-depth:
    value: 4
  reward-type:
    value: "airl-positive"
  ppo-hidden-dim:
    value: 256
  label-dim:
    value: 10