project: 'push-project'
program: deps/baselines/main.py
method: grid
name: Pick-ebil
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --use-proper-time-limits

parameters:
  seed:
    values: [1, 2, 3, 4, 5]
  alg:
    value: ebil
  prefix:
    value: ebil
  env-name:
    value: FetchPickAndPlaceDiffHoldout-v0
  num-mini-batch:
    value: 32
  num-epochs:
    value: 10
  n-ebil-epochs:
    value: 10
  entropy-coef:
    value: 0.001
  cuda:
    value: True
  traj-load-path:
    value: modril/expert_datasets/push.pt
  energy-path:
    value: data/pre/push/ebm/trained_models/push_deen.pt
  lr:
    value: 1e-4
  disc-lr:
    value: 0.001
  eval-num-processes:
    value: 1
  num-render:
    value: 1
  num-env-steps:
    value: 10000000
  ebil-reward-norm:
    value: False
  num-eval:
    value: 100
  eval-interval:
    value: 1000
  save-interval:
    value: 1000
  ebil-state-norm:
    value: True