project: 'push-project'
program: deps/baselines/main.py
method: grid
name: Push-gail
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --use-proper-time-limits

parameters:
  seed:
    values: [1, 2, 3, 4, 5]
  prefix:
    value: gail
  alg:
    value: gail
  traj-load-path:
    value: modril/expert_datasets/push.pt
  env-name:
    value: FetchPushEnvCustom-v0
  normalize-env:
    value: True
  cuda:
    value: True
  eval-num-processes:
    value: 10
  num-render:
    value: 0
  num-eval:
    value: 10
  vid-fps:
    value: 100
  log-interval:
    value: 1
  save-interval:
    value: 100000
  eval-interval:
    value: 2000
  clip-actions:
    value: False
  traj-batch-size:
    value: 128
  max-grad-norm:
    value: 0.5
  num-env-steps:
    value: 10000000
  traj-frac:
    value: 1
  action-input:
    value: True
  entropy-coef:
    value: 0.001
  num-steps:                # Update policy storage's length
    value: 128
  num-epochs:               # Update policy epock
    value: 10
  num-mini-batch:           # For update policy
    value: 32
  gail-state-norm:
    value: True
  gail-reward-norm:
    value: True
  lr:
    value: 0.0001
  disc-lr:
    value: 0.0001
  ppo-hidden-dim:
    value: 256