project: 'pick-project'
program: deps/baselines/main.py
method: grid
name: Pick-drail
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --use-proper-time-limits

parameters:
  prefix:
    value: drail
  alg:
    value: drail
  num-mini-batch:
    value: 32
  entropy-coef:
    value: 0.0001
  action-input:
    value: True
  env-name:
    value: FetchPickAndPlaceDiffHoldout-v0
  num-env-steps:
    value: 25000000
  drail-reward-norm:
    value: False
  cuda:
    value: False
  traj-load-path:
    value: modril/expert_datasets/pick_partial3.pt
  eval-num-processes:
    value: 1
  num-render:
    value: 1
  num-eval:
    value: 100
  eval-interval:
    value: 1000
  save-interval:
    value: 1000
  drail-state-norm:
    value: True
  lr:
    value: 0.0002
  disc-lr:
    value: 0.0001
  num-epochs:
    value: 5
  n-drail-epochs:
    value: 5
  discrim-depth:
    value: 3
  seed:
    values: [1,2,3,4,5]