project: 'modril-project'
program: deps/baselines/main.py
method: grid
name: Ant-gail-0.01
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --use-proper-time-limits
  - --render-metric 

parameters:
  prefix:
    value: gail
  alg:
    value: gail
  env-name:
    value: AntGoal-v0
  traj-load-path:
    value: modril/expert_datasets/ant_50.pt
  cuda:
    value: True
  num-steps:
    value: 500
  traj-frac:
    value: 0.5
  action-input:
    value: True
  num-epochs:
    value: 10
  num-mini-batch:
    value: 32
  gail-reward-norm:
    value: True
  entropy-coef:
    value: 0.001
  lr:
    value: 0.0001
  disc-lr:
    value: 0.0001
  ppo-hidden-dim:
    value: 256
  seed: 
    values: [1,2,3,4,5]
  num-env-steps:
    value: 1000000