project: 'hand-project'
program: deps/baselines/main.py
method: grid
name: Hand-gail
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --use-proper-time-limits

parameters:
  prefix:
    value: gail
  alg:
    value: gail
  num-mini-batch:
    value: 32
  entropy-coef:
    value: 0.0001
  action-input:
    value: True
  env-name:
    value: CustomHandManipulateBlockRotateZ-v0
  gail-reward-norm:
    value: False
  cuda:
    value: True
  traj-load-path:
    value: modril/expert_datasets/hand_10000.pt
  eval-num-processes:
    value: 1
  num-render:
    value: 1
  num-eval:
    value: 100
  eval-interval:
    value: 1000
  save-interval:
    value: 1000
  gail-state-norm:
    value: True
  lr:
    value: 0.0001
  disc-lr:
    value: 0.0001
  num-epochs:
    value: 5
  n-gail-epochs:
    value: 5
  discrim-depth:
    value: 3
  discrim-num-unit:
    value: 128
  seed:
    values: [1,2,3,4,5]