project: 'sine-project'
program: deps/baselines/main.py
method: grid
name: Sine-ebil
command:
  - ${env}
  - python3
  - ${program}
  - ${args}

parameters:
  seed:
    value: 1
  alg:
    value: ebil
  prefix:
    value: ebil
  env-name:
    value: Sine-v0
  num-mini-batch:
    value: 32
  num-epochs:
    value: 10
  entropy-coef:
    value: 0.001
  cuda:
    value: False
  eval-interval:
    value: 1
  save-interval:
    value: 100
  traj-load-path:
    value: modril/expert_datasets/sine.pt
  energy-path:
    value: data/pre/sine/ebm/trained_models/sine_deen.pt
  lr:
    value: 1e-6
  disc-lr:
    value: 0.001
  eval-num-processes:
    value: 1
  num-eval:
    value: 10
  num-env-steps:
    value: 5000000
  ebil-state-norm:
    value: False