project: 'fm-project'
program: deps/baselines/main.py
method: grid
name: Sine-gail
command:
  - ${env}
  - python3
  - ${program}
  - ${args}

parameters:
  seed:
    value: 1
  alg:
    value: gail
  prefix:
    value: gail
  env-name:
    value: Sine-v0
  num-mini-batch:
    value: 32
  num-epochs:
    value: 10
  entropy-coef:
    value: 0.001
  action-input:
    value: True
  gail-reward-norm:
    value: True
  cuda:
    value: False
  eval-interval:
    value: 1
  save-interval:
    value: 100
  traj-load-path:
    value: ./expert_datasets/sine.pt
  lr:
    value: 1e-6
  disc-lr:
    value: 0.001
  eval-num-processes:
    value: 1
  num-eval:
    value: 10
  num-env-steps:
    value: 5000000
  gail-state-norm:
    value: False