project: 'pick-project'
program: deps/baselines/main.py
method: grid
name: Pick-bcf
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --use-proper-time-limits

parameters:
  prefix:
    value: bcf
  alg:
    value: bcf
  env-name:
    value: FetchPickAndPlaceDiffHoldout-v0
  eval-num-processes:
    value: 1
  num-render:
    value: 1
  num-eval:
    value: 100
  cuda:
    value: True
  eval-interval:
    value: 500
  save-interval:
    value: 1000
  traj-val-ratio:
    value: 0
  traj-load-path:
    value: modril/expert_datasets/pick.pt
  normalize-env:
    value: False
  bc-num-epochs:
    value: 1000
  lr:
    value: 0.0008
  depth:
    value: 3
  num-env-steps:
    value: 10000000
  seed:
    values: [1,2,3,4,5]