project: 'modril-project'
program: modril/baselines/main.py
method: grid
name: Ant-drail-0.00
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --use-proper-time-limits
  - --render-metric 

parameters:
  prefix:
    value: drail
  alg:
    value: drail
  env-name:
    value: AntGoal-v0
  traj-load-path:
    value: ./expert_datasets/ant_50.pt
  cuda:
    value: True
  save-interval:
    value: 100000
  num-steps:
    value: 500
  traj-frac:
    value: 0.5
  ant-noise:
    value: 0.0
  action-input:
    value: True
  num-epochs:
    value: 10
  num-mini-batch:
    value: 32
  drail-reward-norm:
    value: True
  entropy-coef:
    value: 0.001
  lr:
    value: 0.0001
  disc-lr:
    value: 0.001
  discrim-num-unit:
    value: 1024
  depth: 
    value: 4
  ppo-hidden-dim:
    value: 256
  seed: 
    values: [1,2,3,4,5]
  reward-type:
    value: "airl"
  num-env-steps:
    value: 10000000