project: 'modril-project'
program: modril/baseline/main.py
method: grid
name: Ant-BC-0.01
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --use-proper-time-limits
  
parameters:
  prefix:
    value: bc
  alg:
    value: bc
  env-name:
    value: AntGoal-v0
  normalize-env:
    value: False
  traj-load-path:
    value: ./expert_datasets/ant_50.pt
  bc-num-epochs:
    value: 1000
  eval-num-processes:
    value: 20
  ant-noise:
    value: 0.01
  traj-frac:
    value: 0.5
  traj-val-ratio:
    value: 0.2
  seed:
    values: [1,2,3,4,5]