project: 'modril-project'
program: modril/baseline/main.py
method: grid
name: "AntGoal-dp-0.00"
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --use-proper-time-limits

parameters:
  prefix:
    value: dp
  alg:
    value: dp
  env-name:
    value: AntGoal-v0
  normalize-env:
    value: False
  traj-load-path:
    value: ./expert_datasets/ant_50.pt
  bc-num-epochs:
    value: 10000
  eval-interval:
    value: 100000 
  eval-num-processes:
    value: 10 
  ant-noise:
    value: 0.0
  traj-frac:
    value: 0.5
  traj-val-ratio:
    value: 0.2
  lr:
    value: 0.00001
  hidden-dim:
    value: 1200
  depth:
    value: 5
  seed:
    values: [1,2,3,4,5]